2020-06-19 21:15:03,404-__main__-INFO-Start study logging
2020-06-19 21:15:03,404-__main__-WARNING-Do something
2020-06-19 21:15:03,404-__main__-INFO-Finish
2020-06-19 21:15:12,615-__main__-INFO-Start study logging
2020-06-19 21:15:12,615-__main__-WARNING-Do something
2020-06-19 21:15:12,615-__main__-INFO-Finish
2020-06-19 21:21:19,993-__man__-INFO-Start study logging
2020-06-19 21:21:19,993-_min__-WARNING-Do something
2020-06-19 21:21:19,994-__main__-INFO-Finishai
_2020-06-19 21:30:06,690-__main__-INFO-Start study logging
2020-06-19 21:30:06,690-__main__-WARNING-Do something
2020-06-19 21:30:06,690-__main__-INFO-Finish
2020-06-19 21:46:44,073-__main__-INFO-Start study logging
2020-06-19 21:46:44,073-__main__-WARNING-Do something
2020-06-19 21:46:44,076-__main__-INFO-Finish
2020-06-19 21:46:44,076-__main__-ERROR-Faild to open yolo.txt from logger.error
Traceback (most recent call last):
  File "D:/Git/learngit/unittest/loggingStudy/logging05.py", line 41, in <module>
    open('yolo.txt', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'yolo.txt'
2020-06-19 21:49:51,778-__main__-INFO-Start study logging
2020-06-19 21:49:51,778-__main__-WARNING-Do something
2020-06-19 21:49:51,778-__main__-INFO-Finish
2020-06-19 21:49:51,778-__main__-ERROR-Faild to open yolo.txt from logger.error
Traceback (most recent call last):
  File "D:/Git/learngit/unittest/loggingStudy/logging05.py", line 41, in <module>
    open('yolo.txt', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'yolo.txt'
2020-06-19 21:49:51,778-__main__-ERROR-Faild to open yolo.txt from logger.error
Traceback (most recent call last):
  File "D:/Git/learngit/unittest/loggingStudy/logging05.py", line 41, in <module>
    open('yolo.txt', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'yolo.txt'
2020-06-19 21:50:12,557-__main__-INFO-Start study logging
2020-06-19 21:50:12,558-__main__-WARNING-Do something
2020-06-19 21:50:12,558-__main__-INFO-Finish
2020-06-19 21:50:12,558-__main__-ERROR-Faild to open yolo.txt from logger.error
Traceback (most recent call last):
  File "D:/Git/learngit/unittest/loggingStudy/logging05.py", line 41, in <module>
    open('yolo.txt', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'yolo.txt'
